; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "MyGame2021180036"
#define MyAppVersion "1.5"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "main.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{63C0248C-73D0-47BD-9504-455F02920ADA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\2DGP\2DGP-Project\temp
OutputBaseFilename=MyGameSetup2021180036
SolidCompression=yes
WizardStyle=modern dark

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\2DGP\2DGP-Project\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\font\ENCR10B.TTF"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\daytime.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\exclamation_mark.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\girl1_Idle.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\girl1_Walk.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\girl2_Idle.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\girl2_Walk.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\girl3_Idle.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\girl3_Walk.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\stair.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\timer.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\title.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\image\tuk.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\sound\bgm.mp3"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP-Project\dist\sound\gameover.mp3"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Dirs]
Name: {app}; Permissions: users-full